-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PSwiki.Object.Experience exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PSwiki.InputObject
import PSwiki.Interface
import PSwiki.Object
import PSwiki.Scalar
import PSwiki.ScalarCodecs
import PSwiki.Union


substances :
    SelectionSet decodesTo PSwiki.Object.Substance
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PSwiki.Object.Experience
substances object____ =
    Object.selectionForCompositeField "substances" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


effects :
    SelectionSet decodesTo PSwiki.Object.Experience
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PSwiki.Object.Experience
effects object____ =
    Object.selectionForCompositeField "effects" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
