-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PSwiki.Object.Substance exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PSwiki.InputObject
import PSwiki.Interface
import PSwiki.Object
import PSwiki.Scalar
import PSwiki.ScalarCodecs
import PSwiki.Union


name : SelectionSet (Maybe String) PSwiki.Object.Substance
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


url : SelectionSet (Maybe String) PSwiki.Object.Substance
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)


featured : SelectionSet (Maybe Bool) PSwiki.Object.Substance
featured =
    Object.selectionForField "(Maybe Bool)" "featured" [] (Decode.bool |> Decode.nullable)


effects :
    SelectionSet decodesTo PSwiki.Object.Effect
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PSwiki.Object.Substance
effects object____ =
    Object.selectionForCompositeField "effects" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


experiences :
    SelectionSet decodesTo PSwiki.Object.Experience
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PSwiki.Object.Substance
experiences object____ =
    Object.selectionForCompositeField "experiences" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


class :
    SelectionSet decodesTo PSwiki.Object.SubstanceClass
    -> SelectionSet (Maybe decodesTo) PSwiki.Object.Substance
class object____ =
    Object.selectionForCompositeField "class" [] object____ (identity >> Decode.nullable)


tolerance :
    SelectionSet decodesTo PSwiki.Object.SubstanceTolerance
    -> SelectionSet (Maybe decodesTo) PSwiki.Object.Substance
tolerance object____ =
    Object.selectionForCompositeField "tolerance" [] object____ (identity >> Decode.nullable)


roa :
    SelectionSet decodesTo PSwiki.Object.SubstanceRoaTypes
    -> SelectionSet (Maybe decodesTo) PSwiki.Object.Substance
roa object____ =
    Object.selectionForCompositeField "roa" [] object____ (identity >> Decode.nullable)


roas :
    SelectionSet decodesTo PSwiki.Object.SubstanceRoa
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PSwiki.Object.Substance
roas object____ =
    Object.selectionForCompositeField "roas" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


summary : SelectionSet (Maybe String) PSwiki.Object.Substance
summary =
    Object.selectionForField "(Maybe String)" "summary" [] (Decode.string |> Decode.nullable)


images :
    SelectionSet decodesTo PSwiki.Object.SubstanceImage
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PSwiki.Object.Substance
images object____ =
    Object.selectionForCompositeField "images" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


addictionPotential : SelectionSet (Maybe String) PSwiki.Object.Substance
addictionPotential =
    Object.selectionForField "(Maybe String)" "addictionPotential" [] (Decode.string |> Decode.nullable)


toxicity : SelectionSet (Maybe (List (Maybe String))) PSwiki.Object.Substance
toxicity =
    Object.selectionForField "(Maybe (List (Maybe String)))" "toxicity" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


crossTolerances : SelectionSet (Maybe (List (Maybe String))) PSwiki.Object.Substance
crossTolerances =
    Object.selectionForField "(Maybe (List (Maybe String)))" "crossTolerances" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


uncertainInteractions :
    SelectionSet decodesTo PSwiki.Object.Substance
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PSwiki.Object.Substance
uncertainInteractions object____ =
    Object.selectionForCompositeField "uncertainInteractions" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


unsafeInteractions :
    SelectionSet decodesTo PSwiki.Object.Substance
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PSwiki.Object.Substance
unsafeInteractions object____ =
    Object.selectionForCompositeField "unsafeInteractions" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


dangerousInteractions :
    SelectionSet decodesTo PSwiki.Object.Substance
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PSwiki.Object.Substance
dangerousInteractions object____ =
    Object.selectionForCompositeField "dangerousInteractions" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
