-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PSwiki.Object.SubstanceRoa exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PSwiki.InputObject
import PSwiki.Interface
import PSwiki.Object
import PSwiki.Scalar
import PSwiki.ScalarCodecs
import PSwiki.Union


name : SelectionSet (Maybe String) PSwiki.Object.SubstanceRoa
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


dose :
    SelectionSet decodesTo PSwiki.Object.SubstanceRoaDose
    -> SelectionSet (Maybe decodesTo) PSwiki.Object.SubstanceRoa
dose object____ =
    Object.selectionForCompositeField "dose" [] object____ (identity >> Decode.nullable)


duration :
    SelectionSet decodesTo PSwiki.Object.SubstanceRoaDuration
    -> SelectionSet (Maybe decodesTo) PSwiki.Object.SubstanceRoa
duration object____ =
    Object.selectionForCompositeField "duration" [] object____ (identity >> Decode.nullable)


bioavailability :
    SelectionSet decodesTo PSwiki.Object.SubstanceRoaRange
    -> SelectionSet (Maybe decodesTo) PSwiki.Object.SubstanceRoa
bioavailability object____ =
    Object.selectionForCompositeField "bioavailability" [] object____ (identity >> Decode.nullable)
