-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PSwiki.Object.SubstanceRoaRange exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PSwiki.InputObject
import PSwiki.Interface
import PSwiki.Object
import PSwiki.Scalar
import PSwiki.ScalarCodecs
import PSwiki.Union


min : SelectionSet (Maybe Float) PSwiki.Object.SubstanceRoaRange
min =
    Object.selectionForField "(Maybe Float)" "min" [] (Decode.float |> Decode.nullable)


max : SelectionSet (Maybe Float) PSwiki.Object.SubstanceRoaRange
max =
    Object.selectionForField "(Maybe Float)" "max" [] (Decode.float |> Decode.nullable)
