-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PSwiki.Object.SubstanceImage exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PSwiki.InputObject
import PSwiki.Interface
import PSwiki.Object
import PSwiki.Scalar
import PSwiki.ScalarCodecs
import PSwiki.Union


thumb : SelectionSet (Maybe String) PSwiki.Object.SubstanceImage
thumb =
    Object.selectionForField "(Maybe String)" "thumb" [] (Decode.string |> Decode.nullable)


image : SelectionSet (Maybe String) PSwiki.Object.SubstanceImage
image =
    Object.selectionForField "(Maybe String)" "image" [] (Decode.string |> Decode.nullable)
