-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PSwiki.Object.SubstanceRoaDurationRange exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PSwiki.InputObject
import PSwiki.Interface
import PSwiki.Object
import PSwiki.Scalar
import PSwiki.ScalarCodecs
import PSwiki.Union


min : SelectionSet (Maybe Float) PSwiki.Object.SubstanceRoaDurationRange
min =
    Object.selectionForField "(Maybe Float)" "min" [] (Decode.float |> Decode.nullable)


max : SelectionSet (Maybe Float) PSwiki.Object.SubstanceRoaDurationRange
max =
    Object.selectionForField "(Maybe Float)" "max" [] (Decode.float |> Decode.nullable)


units : SelectionSet (Maybe String) PSwiki.Object.SubstanceRoaDurationRange
units =
    Object.selectionForField "(Maybe String)" "units" [] (Decode.string |> Decode.nullable)
