-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PSwiki.Object exposing (..)


type Effect
    = Effect


type Experience
    = Experience


type Substance
    = Substance


type SubstanceClass
    = SubstanceClass


type SubstanceImage
    = SubstanceImage


type SubstanceRoa
    = SubstanceRoa


type SubstanceRoaDose
    = SubstanceRoaDose


type SubstanceRoaDuration
    = SubstanceRoaDuration


type SubstanceRoaDurationRange
    = SubstanceRoaDurationRange


type SubstanceRoaRange
    = SubstanceRoaRange


type SubstanceRoaTypes
    = SubstanceRoaTypes


type SubstanceTolerance
    = SubstanceTolerance
